
ERROR_CMD_PARAMS = -2

ERROR_UNKOWN = -1
SUCCESS = 0
ERROR_TX_PUBLISHED = 1
ERROR_DUST_TX = 2
ERROR_INSUFFICIENT_BALANCE = 3
ERROR_NETWORK = 4

ERROR_NET_TYPE_NOT_SUPPORTED = 5
ERROR_UNFINISHED_CODE = 6

ERROR_GET_TX_FAILED = 7

ERROR_VERIFY_SIG_FAILED = 8
